-- run this in snoflake account worksheet--
CREATE DATABASE IF NOT EXISTS OEE_COMMAND_CENTER;
USE DATABASE OEE_COMMAND_CENTER;
CREATE SCHEMA IF NOT EXISTS FACTORY_FLOOR;
USE SCHEMA FACTORY_FLOOR;

CREATE OR REPLACE TABLE RAW_IT_BATCHES (
    BATCH_ID VARCHAR,
    SKU_ID VARCHAR,
    EQUIPMENT_ID VARCHAR,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_OT_TELEMETRY (
    TIMESTAMP TIMESTAMP_NTZ,
    EQUIPMENT_ID VARCHAR,
    TEMPERATURE_C FLOAT,
    VIBRATION_RMS FLOAT
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE FACTORY_DATA_STAGE
    FILE_FORMAT = CSV_FORMAT;

-- ── 2. Dynamic Tables (Transformations) ───────────────────────────────────────
-- Transforms the isolated streams into a converged state
CREATE OR REPLACE DYNAMIC TABLE IT_OT_CONVERGED
    TARGET_LAG = '1 minute'
    WAREHOUSE = 'COMPUTE_WH'
AS
SELECT
    ot.TIMESTAMP,
    ot.EQUIPMENT_ID,
    ot.TEMPERATURE_C,
    ot.VIBRATION_RMS,
    COALESCE(it.BATCH_ID, 'CHANGEOVER/IDLE') AS BATCH_ID,
    COALESCE(it.SKU_ID, 'NONE') AS SKU_ID
FROM RAW_OT_TELEMETRY ot
LEFT JOIN RAW_IT_BATCHES it
    ON ot.EQUIPMENT_ID = it.EQUIPMENT_ID
    AND ot.TIMESTAMP BETWEEN it.START_TIME AND it.END_TIME;

-- ── 2. Auxiliary Tables ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS OEM_EQUIPMENT_THRESHOLDS (
    EQUIPMENT_ID VARCHAR,
    SKU_ID VARCHAR,
    MAX_TEMP_LIMIT FLOAT,
    MAX_VIBRATION_LIMIT FLOAT,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OEM_MANUAL_CHUNKS (
    FILE_NAME VARCHAR,
    CHUNK_INDEX INTEGER,
    CHUNK_TEXT VARCHAR
);

CREATE TABLE IF NOT EXISTS ALERTS_HISTORY (
    TIMESTAMP         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EQUIPMENT_ID      VARCHAR,
    SKU_ID            VARCHAR,
    ACTION_TAKEN      VARCHAR,
    PRIORITY          VARCHAR,
    RUL_HOURS         FLOAT,
    OEM_CONSTRAINTS   VARCHAR,
    STATUS            VARCHAR
);

-- ── 3. Auxiliary Stages ───────────────────────────────────────────────────────
CREATE OR REPLACE STAGE OEM_MANUALS_STAGE DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS SEMANTIC_MODELS_STAGE DIRECTORY = (ENABLE = TRUE);