--aggregate your dynamic table into hourly intervals, capturing the equipment ID, average temperature, and average vibration.--
USE DATABASE OEE_COMMAND_CENTER;
USE SCHEMA FACTORY_FLOOR;



CREATE OR REPLACE VIEW V_EQUIPMENT_TEMP_HISTORY AS
SELECT 
    DATE_TRUNC('HOUR', TIMESTAMP) AS TS_HOUR,
    EQUIPMENT_ID,
    AVG(TEMPERATURE_C) AS AVG_TEMP
FROM IT_OT_CONVERGED
GROUP BY 1, 2;

CREATE OR REPLACE VIEW V_EQUIPMENT_VIBE_HISTORY AS
SELECT 
    DATE_TRUNC('HOUR', TIMESTAMP) AS TS_HOUR,
    EQUIPMENT_ID,
    AVG(VIBRATION_RMS) AS AVG_VIBE
FROM IT_OT_CONVERGED
GROUP BY 1, 2;

--generate independent forecasts for every unique piece of equipment in your dataset.--
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST EQUIPMENT_TEMP_FORECAST (
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'V_EQUIPMENT_TEMP_HISTORY'),
    SERIES_COLNAME => 'EQUIPMENT_ID',
    TIMESTAMP_COLNAME => 'TS_HOUR',
    TARGET_COLNAME => 'AVG_TEMP'
);

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST EQUIPMENT_VIBE_FORECAST (
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'V_EQUIPMENT_VIBE_HISTORY'),
    SERIES_COLNAME => 'EQUIPMENT_ID',
    TIMESTAMP_COLNAME => 'TS_HOUR',
    TARGET_COLNAME => 'AVG_VIBE'
);

--flags the exact hour the forecasted metrics breach the critical OEM threshold--
-- Generate predictions for the next 72 hours and store them in a table
CREATE OR REPLACE TABLE PREDICTED_TEMPERATURES AS
SELECT * FROM TABLE(EQUIPMENT_TEMP_FORECAST!FORECAST(FORECASTING_PERIODS => 72));

CREATE OR REPLACE TABLE PREDICTED_VIBRATIONS AS
SELECT * FROM TABLE(EQUIPMENT_VIBE_FORECAST!FORECAST(FORECASTING_PERIODS => 72));

-- Calculate Remaining Useful Life (RUL) by finding the first breach
CREATE OR REPLACE VIEW ASSET_RUL_PREDICTIONS AS
WITH active_sku AS (
    SELECT EQUIPMENT_ID, SKU_ID
    FROM IT_OT_CONVERGED
    WHERE BATCH_ID != 'CHANGEOVER/IDLE'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EQUIPMENT_ID ORDER BY TIMESTAMP DESC) = 1
),
sku_thresholds AS (
    SELECT
        a.EQUIPMENT_ID,
        COALESCE(s.MAX_TEMP_LIMIT, e.MAX_TEMP_LIMIT, g.MAX_TEMP_LIMIT, 90.0) AS TEMP_THRESHOLD,
        COALESCE(s.MAX_VIBRATION_LIMIT, e.MAX_VIBRATION_LIMIT, g.MAX_VIBRATION_LIMIT, 2.3) AS VIBE_THRESHOLD
    FROM active_sku a
    LEFT JOIN OEM_EQUIPMENT_THRESHOLDS s
        ON a.EQUIPMENT_ID = s.EQUIPMENT_ID AND a.SKU_ID = s.SKU_ID
    LEFT JOIN OEM_EQUIPMENT_THRESHOLDS e
        ON a.EQUIPMENT_ID = e.EQUIPMENT_ID AND e.SKU_ID = 'ALL'
    LEFT JOIN OEM_EQUIPMENT_THRESHOLDS g
        ON g.EQUIPMENT_ID = 'ALL' AND g.SKU_ID = 'ALL'
),
temp_rul AS (
    SELECT 
        p.SERIES AS EQUIPMENT_ID,
        MIN(p.TS) AS PREDICTED_FAILURE_TIMESTAMP,
        GREATEST(1, ROUND(TIMEDIFF('HOUR', CURRENT_TIMESTAMP(), MIN(p.TS)), 1)) AS RUL_HOURS,
        'Temperature Forecast Breach' AS PREDICTIVE_CAUSE
    FROM PREDICTED_TEMPERATURES p
    INNER JOIN sku_thresholds t ON p.SERIES = t.EQUIPMENT_ID
    WHERE p.FORECAST >= t.TEMP_THRESHOLD
    GROUP BY p.SERIES
),
vibe_rul AS (
    SELECT 
        p.SERIES AS EQUIPMENT_ID,
        MIN(p.TS) AS PREDICTED_FAILURE_TIMESTAMP,
        GREATEST(1, ROUND(TIMEDIFF('HOUR', CURRENT_TIMESTAMP(), MIN(p.TS)), 1)) AS RUL_HOURS,
        'Vibration Forecast Breach' AS PREDICTIVE_CAUSE
    FROM PREDICTED_VIBRATIONS p
    INNER JOIN sku_thresholds t ON p.SERIES = t.EQUIPMENT_ID
    WHERE p.FORECAST >= t.VIBE_THRESHOLD
    GROUP BY p.SERIES
),
combined_rul AS (
    SELECT * FROM temp_rul
    UNION ALL
    SELECT * FROM vibe_rul
)
-- Take the earliest predicted failure for each equipment
SELECT 
    EQUIPMENT_ID,
    PREDICTED_FAILURE_TIMESTAMP,
    RUL_HOURS,
    PREDICTIVE_CAUSE
FROM combined_rul
QUALIFY ROW_NUMBER() OVER (PARTITION BY EQUIPMENT_ID ORDER BY RUL_HOURS ASC) = 1;