USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE CORTEX SEARCH SERVICE OEM_MANUAL_SEARCH
    ON CHUNK_TEXT
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    AS
    SELECT
        FILE_NAME,
        CHUNK_INDEX,
        CHUNK_TEXT
    FROM OEM_MANUAL_CHUNKS;